name: Package GEDKeeper3 for Fedora

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fedora:

    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - name: Insall Prerequisites
      run: dnf install git-all dotnet-sdk-6.0 rpm-build -y
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: chmod +x ./make_gk3_linux_fedora_pack.sh && ./make_gk3_linux_fedora_pack.sh
      working-directory: deploy
#    - name: Upload DMG file
#      uses: actions/upload-artifact@v3
#      with:
#        name: GEDKeeper3
#        path: projects/GKv3/GEDKeeper3/bin/MacOS_Debug/*.dmg
#        if-no-files-found: error
