name: Package GEDKeeper3 for MacOS

on:
  push:
    branches: [ "mac" ]
  pull_request:
    branches: [ "mac" ]

jobs:
  mac:
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - uses: apple-actions/import-codesign-certs@v3
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

    - name: Build
      run: dotnet build GEDKeeper3.sln -c=Release -p:Platform=MacOS -p:EnableDmgBuild=true -p:GKEnableCodeSigning=true -p:GKMacCodeSigninKey=GEDKeeper2
      working-directory: projects/GKv3

    - name: Upload DMG file
      uses: actions/upload-artifact@v4
      with:
        name: GEDKeeper3
        path: projects/GKv3/GEDKeeper3/bin/MacOS/Release/*.dmg
        if-no-files-found: error
